name: "CI/CD: Build and Deploy to Cloud Run"

on:
  repository_dispatch:
    types: [update_blog]
  push:
    branches: [master, dev]
    paths-ignore: ['src/content/posts/**', 'public/images/blog/**']

env:
  PROJECT_ID: poetic-avenue-438401-a7
  REGION: us-east1
  REPO_NAME: nucleus-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Environment
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            # Blogs push always goes to dev
            echo "TARGET_BRANCH=dev" >> $GITHUB_ENV
          else
            # Code push follows the branch (master or dev)
            echo "TARGET_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Checkout Website
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: ${{ env.TARGET_BRANCH }}

      - name: Checkout Blogs (Master only)
        uses: actions/checkout@v4
        with:
          repository: WithNucleusAI/engineering-blogs
          token: ${{ secrets.GH_PAT }}
          path: temp_blogs
          ref: master # Always pull blogs from master

      - name: Setup Node & Process Blogs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Build & Push Docker Image
        run: |
          TAG="${{ env.TARGET_BRANCH }}-${{ github.sha }}"
          IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/nucleus-blog:${TAG}"
          
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_URL=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: nucleus-blog-${{ env.TARGET_BRANCH }}
          image: ${{ env.IMAGE_URL }}
          region: ${{ env.REGION }}
          flags: '--allow-unauthenticated'