name: Build and Deploy

on:
  repository_dispatch:
    types: [update_blog]
  workflow_dispatch:
  push:
    branches: [master, dev]
    paths-ignore:
      - 'src/content/posts/**'
      - 'public/images/blog/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Checkout Blogs Repo
        uses: actions/checkout@v4
        with:
          repository: WithNucleusAI/engineering-blogs
          token: ${{ secrets.GH_PAT }}
          path: temp_blogs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Project Deps
        run: npm ci

      - name: Install Puppeteer System Dependencies
        run: npx puppeteer browsers install chrome

      - name: Process Blogs
        run: node scripts/process-blogs.mjs

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WITHNUCLEUSAI_GITHUB_IO }}'
          channelId: live
          projectId: poetic-avenue-438401-a7